import type { ToastOptions } from 'react-toastify'
import { Slide } from 'react-toastify'

// import config from '../../public/configuration.json';
const config = await fetch('/configuration.json').then((res) => res.json())

export const BASE_REPORT_URL = `${config?.httpProtocol}://${config.serverAddress}:${config.serverPort}/api`
// **************** ROUTE CONSTANT START **************************
// General Page Section
export const DASHBOARD = '/dashboard'
export const PERSONNEL = '/personnel'
export const PRODUCT = '/product/:id'
export const PRODUCT_FORM = '/product'
export const DEPARTMENTS = '/departments'
export const CATEGORY = '/categories'
export const LOGIN = '/login'
export const VERIFY_EMAIL = '/verify-email'
export const LOGOUT = '/logout'
export const ORDERS = '/orders'
export const VENDORS = '/vendors'
export const VENDOR = '/vendor/:id'
export const SHOPS = '/shops'
export const COUPONS = '/coupons'
export const SETTINGS = '/settings'
export const VENDOR_SETTINGS = '/vendor-settings'
export const USER = '/users/:id'
export const PERMISSIONS = '/permissions'
export const STAFF_MEMBERS = '/staff-members'
export const SITE_SETTINGS = '/site-settings'
export const SIGNIN = '/sign-in'
export const SHARE_LINK = '/share-link'
export const VENDOR_TEAM = '/vendor-team'
export const VENDOR_INVITATION = '/invites/:id'
export const ATTRIBUTES = '/attributes'
// export const SUPPLIERS = "/suppliers";
export const SUPPLIER_CATEGORIES = '/supplier-categories'
export const SCHOOL_YEARS = '/school-years'
export const SCHOOL_LIABLE = '/school-liable'
export const SCHOOL_SECTIONS = '/school-sections'
export const CLASSES = '/classes'
export const BRANCHES = '/branches'
export const LEVELS = '/levels'
export const CYCLES = '/cycles'
export const USERS = '/users'
export const LOGIN_HISTORIES = '/login-histories'
export const ROLES = '/roles'
export const USER_GROUPS = '/user-groups'
export const SUBJECTS = '/subjects'
export const SUBJECT_DEPARTMENTS = '/departments'
export const SUBJECT_GROUPS = '/subject-groups'
export const PERIODS = '/periods'
export const SUB_PERIODS = '/sub-periods'
export const FREQUENTS = '/frequents'
export const STUDENTS = '/students'
export const GUARDIANS = '/guardians'
export const PAYMENT_GROUPS = '/payment-groups'
export const PAYMENT_SLICES = '/payment-slices'
export const PAYMENT_MODE = '/payment-modes'
export const SCHOOL_FEES = '/payment-school-fees'
export const SCHOOL_FEE_LEVELS = '/payment-school-fee-levels'
export const SCHOOL_FEE_LEVELS_2 = '/payment-school-fee-levels-2'
export const EXPECTED_COMPETENCES = '/competences'
export const SEQUENTIAL_NOTES = '/sequential-notes'
export const SEQUENTIAL_NOTE_COPY = '/sequential-note-copy'
export const SEQUENTIAL_NOTE_DOWNGRADE = '/sequential-note-downgrade'
export const SEQUENTIAL_NOTE_DELETE = '/sequential-note-delete'
export const SEQUENTIAL_NOTE_TEMPLATE = '/sequential-note-template'
export const SEQUENTIAL_NOTE_IMPORT = '/sequential-note-import'
export const QUARTERLY_REPORT_OBSERVATION = '/quarterly-report-observation'
export const ANNUAL_RESULT = '/annual-result'
export const BULK_ANNUAL_RESULT = '/bulk-annual-result'
export const REPORTS = '/reports'
export const DATABASE_BACKUP = '/database-backup'
export const CLASS_DISTRIBUTION = '/distribution'
export const TIME_SLOTS = '/time-slots'
export const TIME_TABLES = '/time-tables'
export const DAY_OF_CLASSES = '/day-of-classes'
export const SCHOOL = '/school'
export const SCHOOL_OFFICIALS = '/school-liable'
export const OFFICIAL_FUNCTIONS = '/liable-type'
export const SEQUENTIAL_DISCIPLINES = '/sequential-discipline'
export const CLONE_CONFIG = '/copyOfParameters'
export const STUDENT_PAYMENTS = '/student-payments'
export const STUDENT_INVOICES = '/student-invoices'
export const PROFILE = '/profile'
export const QR_CODE = '/qrcode'
export const VERIFY_CODE = '/verify'
export const NOT_AUTHORIZED = 'not-authorized'
export const BATCH_PICTURES = '/batch-pictures'
export const STUDENT_PROGRESSION = '/student-progression'
export const CONFIGURATION = '/configuration'
export const COUNCIL_DECISION = '/council-decision'
export const QUARTERLY_NOTES = '/quarterly-notes'
export const OLD_SCHOOLS = '/old-schools'
export const DISCIPLINE_CALCULATION = '/discipline-calculation'
export const QUARTERLY_DISCIPLINE = '/quarterly-discipline'
export const ANNUAL_DISCIPLINE = '/annual-discipline'
export const NOTE_CALCULATION = '/note-calculation'
export const AVERAGE_CALCULATION = '/average-calculation'
export const QUARTERLY_NOTE = '/quarterly-note'
export const QUARTERLY_COMP_NOTE = '/quarterly-comp-note'
export const QUARTERLY_COMP_NOTE_EVAL = '/quarterly-comp-note-eval'
export const ANNUAL_NOTE = '/annual-note'
export const ANNUAL_COMP_NOTE = '/annual-comp-note'
export const SEQUENTIAL_AVERAGE = '/sequential-average'
export const QUARTERLY_AVERAGE = '/quarterly-average'
export const ANNUAL_AVERAGE = '/annual-average'
export const ANNUAL_COMP_AVERAGE = '/annual-comp-average'
export const ANNUAL_NOTES = '/annual-notes'
export const GUIDED_SETUP = '/guided-setup'
export const INIT_SCHOOL = '/start'
export const EVAL_COMP = '/eval-competences'
export const EVAL_COMP_SUBJECT = '/eval-competences-subject'
export const EVAL_TYPES = '/eval-types'
export const COMPETENCES = '/primary-competences'
export const COMPETENCES_LEVEL = '/primary-competences-level'
export const SUB_COMPETENCES = '/sub-competences'
export const P_SEQUENTIAL_NOTES = '/primary-sequential-notes'
export const P_FREE_SEQUENTIAL_NOTES = '/free-primary-sequential-notes'
export const STUDENT_UPDATE_BY_CLASS = '/student-update-by-class'
// export const PERMISSIONS = "/permissions";
export const MOBILE_TUITION = '/tuition/:identifier'
export const MOBILE_PAYMENT_STATUS = '/payment-status/:reference'

// accounting routes
export const ACCOUNT_MODELS = '/models'
export const ACCOUNT_GROUPS = '/account-groups'
export const ACCOUNT_CATEGORIES = '/account-categories'
export const LOG_CODES = '/log-codes'
export const CHART_OF_ACCOUNTS = '/chartOfAccounts'
export const ACCOUNTS = '/accounts'
export const SPECIAL_ACCOUNTS = '/special-accounts'
export const JOURNAL = '/journal'

// payroll routes
export const PAYROLL_EXERCISES = '/payroll-exercises'
export const PAYROLL_CATEGORIES = '/payroll-categories'
export const PAYROLL_PERIODS = '/payroll-periods'
export const PAYROLL_SECTIONS = '/payroll-sections'
export const PAYROLL_DEPARTMENTS = '/payroll-departments'
export const PAYROLL_POSITIONS = '/payroll-positions'
export const PAYROLL_EARNING_CATEGORIES = '/earning-categories'
export const PAYROLL_DEDUCTION_CATEGORIES = '/deduction-categories'
export const PAYROLL_EARNINGS = '/earnings'
export const PAYROLL_DEDUCTIONS = '/deductions'
export const PAYROLL_EMPLOYEES = '/employees'
export const PAYROLLS = '/payrolls'

// reports
export const CLASS_SUMMARY = '/CLASS_SUMMARY'
export const MULTI_COLUMN_STUDENT = '/MULTI_COLUMN_STUDENT'
export const SINGLE_COLUMN_STUDENT = '/SINGLE_COLUMN_STUDENT'
export const ANNUAL_MARK_SHEET = '/ANNUAL_MARK_SHEET'
export const BLANK_NOTE_BOOK = '/BLANK_NOTE_BOOK'
export const SEQUENTIAL_NOTE_BOOK = '/SEQUENTIAL_NOTE_BOOK'
export const SEQUENTIAL_REPORT_CARD = '/SEQUENTIAL_REPORT_CARD'
export const ANNUAL_NTH_FIRST = '/ANNUAL_NTH_FIST'
export const TEACHER_DISTRIBUTION_LEVEL = '/TEACHER_DISTRIBUTION_LEVEL'
export const QUARTERLY_REPORT_SUMMARY = '/QUARTERLY_REPORT_SUMMARY'
export const MARK_SHEET = '/MARK_SHEET'
export const QUARTERLY_MARK_SHEET = '/QUARTERLY_MARK_SHEET'
export const INPUT_PROGRESS = '/INPUT_PROGRESS'
export const QUARTERLY_NOTE_BOOK = '/QUARTERLY_NOTE_BOOK'
export const QUARTERLY_REPORT_CARD = '/QUARTERLY_REPORT_CARD'
export const APPLIED_COEFFICIENTS = '/APPLIED_COEFFICIENTS'
export const SEQUENTIAL_REPORT_SUMMARY = '/SEQUENTIAL_REPORT_SUMMARY'
export const ANNUAL_REPORT_SUMMARY = '/ANNUAL_REPORT_SUMMARY'
export const STUDENT_PAYMENT_DETAIL = '/STUDENT_PAYMENT_DETAIL'
export const STUDENT_PAYMENT_DETAIL_BY_DATE = '/STUDENT_PAYMENT_DETAIL_BY_DATE'
export const ANNUAL_NOTE_BOOK = '/ANNUAL_NOTE_BOOK'
export const ANNUAL_BEST = '/ANNUAL_BEST'
export const ANNUAL_REPORT_CARD = '/ANNUAL_REPORT_CARD'
export const ANNUAL_COMP_REPORT_CARD = '/ANNUAL_COMP_REPORT_CARD'
export const ANNUAL_REPORT_CARD_EXAM = '/ANNUAL_REPORT_CARD_EXAM'
export const ANNUAL_STATISTICS = '/ANNUAL_STATISTICS'
export const ANNUAL_SCHOOL_BOOK = '/ANNUAL_SCHOOL_BOOK'
export const STUDENT_PAYMENT_SUMMARY = '/STUDENT_PAYMENT_SUMMARY'
export const STUDENT_PAYMENT_SLICE_SUMMARY = '/STUDENT_PAYMENT_SLICE_SUMMARY'
export const QUARTERLY_NTH_FIRST = 'QUARTERLY_NTH_FIRST'
export const SEQUENTIAL_NTH_FIRST = 'SEQUENTIAL_NTH_FIRST'
export const PERSONNEL_LIST = 'PERSONNEL_LIST'
export const EXCLUDED_STUDENTS = 'EXCLUDED_STUDENTS'
export const INVOICE_REPORT = 'INVOICE_REPORT'
export const PAYMENT_REPORT = 'PAYMENT_REPORT'
export const PAYMENT_GROUP_REPORT = 'PAYMENT_GROUP_REPORT'
export const SCHOOL_FEE_REPORT = 'SCHOOL_FEE_REPORT'
export const EVALUATED_COMPETENCES = 'EVALUATED_COMPETENCES'
export const QUARTERLY_COMP_REPORT = 'QUARTERLY_COMP_REPORT_CARD'
export const QUARTERLY_HONOR_ROLL = 'QUARTERLY_HONOR_ROLL'
export const FEE_PAYMENT_DETAIL = 'FEE_PAYMENT_DETAIL'
export const FEE_PAYMENT_DETAIL_BY_DATE = 'FEE_PAYMENT_DETAIL_BY_DATE'
export const FEE_PAYMENT_SUMMARY = 'FEE_PAYMENT_SUMMARY'
export const FEE_PAYMENT_SLICE_SUMMARY = 'FEE_PAYMENT_SLICE_SUMMARY'
export const TIME_TABLE = 'TIME_TABLE'
export const TEACHER_TIME_TABLE = 'TEACHER_TIME_TABLE'
export const FEE_PAYMENT_PRODUCT_SUMMARY = 'FEE_PAYMENT_PRODUCT_SUMMARY'
export const FEE_PAYMENT_PRODUCT_CLASS_SUMMARY =
  'FEE_PAYMENT_PRODUCT_CLASS_SUMMARY'
export const FEE_PAYMENT_PRODUCT_STUDENT_SUMMARY =
  'FEE_PAYMENT_PRODUCT_STUDENT_SUMMARY'
export const FEE_PAYMENT_DASHBOARD = 'FEE_PAYMENT_DASHBOARD'
export const WEEKLY_DISCIPLINE = 'WEEKLY_DISCIPLINE'
export const COMPETENCE_INPUT_PROGRESS = 'COMPETENCE_INPUT_PROGRESS'
export const LOGIN_HISTORY = 'LOGIN_HISTORY'
export const ACCOUNT_LIST = 'ACCOUNT_LIST'
export const EXPENSE_REPORT = 'EXPENSE_REPORT'
export const EXPENSE_REPORT_SUMMARY = 'EXPENSE_REPORT_SUMMARY'

// data export
export const DATA_EXPORT = '/data-export'
export const ANNUAL_SCHOOL_BOOK_XLSX = '/annual-school-book-xlsx'
export const PERSONNEL_XSSF = '/personnel-xlsx'
export const STUDENT_XSSF = '/student-xlsx'

// bank
export const BANK_ACCOUNTS = '/bank-accounts'
export const BANK_TRANSACTIONS = '/bank-transactions'

// sale
export const SUPPLIERS = '/suppliers'
export const SUPPLIERS_CATEGORIES = '/supplier-categories'
export const PAYMENT_CONDITIONS = '/payment-conditions'
export const PRODUCT_CATEGORIES = '/product-categories'
export const PRODUCTS = '/products'
export const DISCOUNTS = '/discounts'
export const CUSTOMERS = '/customers'
export const CUSTOMER_CATEGORIES = '/customer-categories'
export const FEE_GROUPS = '/fee-groups'
export const INSTALLMENTS = '/installments'
export const FEE_STRUCTURES = '/fee-structures'
export const HEAD_DEPARTMENTS = '/head-departments'
export const OPERATIONS = '/operations'
export const MOBILE_OPERATIONS = '/mobile-operations'

// expense
export const EXPENSE_CATEGORIES = '/expense-categories'
export const OPERATION_CLASSES = '/operation-classes'
export const CASH_VOUCHERS = '/vouchers'
export const EXPENSES = '/expenses'
export const PURCHASES = '/purchases'

// **************** ROUTE CONSTANT END **************************

export const SHOW_CONFIRM = 'SHOW_CONFIRM'
export const HIDE_CONFIRM = 'HIDE_CONFIRM'
export const INPUT_DATE_FORMAT = 'YYYY-MM-DD'

// *** objects

export const TOAST_OPTIONS: ToastOptions = {
  hideProgressBar: true,
  transition: Slide,
  autoClose: 1000,
}

export const DEFAULT_POLL_INTERVAL = 300 * 1000
