/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateLayoutRouteImport } from './routes/_privateLayout'
import { Route as InitSchoolRouteImport } from './routes/init-school'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotAuthorizedRouteImport } from './routes/not-authorized'
import { Route as PrivateLayoutCleanLayoutRouteImport } from './routes/_privateLayout/_cleanLayout'
import { Route as PrivateLayoutVerticalRouteImport } from './routes/_privateLayout/_vertical'
import { Route as PrivateLayoutCleanLayoutAccount_listRouteImport } from './routes/_privateLayout/_cleanLayout/account_list'
import { Route as PrivateLayoutVerticalConfigurationRouteImport } from './routes/_privateLayout/_vertical/configuration'
import { Route as PrivateLayoutVerticalDashboardRouteImport } from './routes/_privateLayout/_vertical/dashboard'
import { Route as PrivateLayoutVerticalschoolSchoolRouteImport } from './routes/_privateLayout/_vertical/(school)/school'
import { Route as PrivateLayoutVerticalschoolSchoolYearsRouteImport } from './routes/_privateLayout/_vertical/(school)/school-years'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_privateLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const InitSchoolRoute = InitSchoolRouteImport.update({
  id: '/init-school',
  path: '/init-school',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotAuthorizedRoute = NotAuthorizedRouteImport.update({
  id: '/not-authorized',
  path: '/not-authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutCleanLayoutRoute =
  PrivateLayoutCleanLayoutRouteImport.update({
    id: '/_cleanLayout',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateLayoutVerticalRoute = PrivateLayoutVerticalRouteImport.update({
  id: '/_vertical',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutCleanLayoutAccount_listRoute =
  PrivateLayoutCleanLayoutAccount_listRouteImport.update({
    id: '/account_list',
    path: '/account_list',
    getParentRoute: () => PrivateLayoutCleanLayoutRoute,
  } as any)
const PrivateLayoutVerticalConfigurationRoute =
  PrivateLayoutVerticalConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => PrivateLayoutVerticalRoute,
  } as any)
const PrivateLayoutVerticalDashboardRoute =
  PrivateLayoutVerticalDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => PrivateLayoutVerticalRoute,
  } as any)
const PrivateLayoutVerticalschoolSchoolRoute =
  PrivateLayoutVerticalschoolSchoolRouteImport.update({
    id: '/(school)/school',
    path: '/school',
    getParentRoute: () => PrivateLayoutVerticalRoute,
  } as any)
const PrivateLayoutVerticalschoolSchoolYearsRoute =
  PrivateLayoutVerticalschoolSchoolYearsRouteImport.update({
    id: '/(school)/school-years',
    path: '/school-years',
    getParentRoute: () => PrivateLayoutVerticalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/init-school': typeof InitSchoolRoute
  '/login': typeof LoginRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/account_list': typeof PrivateLayoutCleanLayoutAccount_listRoute
  '/configuration': typeof PrivateLayoutVerticalConfigurationRoute
  '/dashboard': typeof PrivateLayoutVerticalDashboardRoute
  '/school': typeof PrivateLayoutVerticalschoolSchoolRoute
  '/school-years': typeof PrivateLayoutVerticalschoolSchoolYearsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/init-school': typeof InitSchoolRoute
  '/login': typeof LoginRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/account_list': typeof PrivateLayoutCleanLayoutAccount_listRoute
  '/configuration': typeof PrivateLayoutVerticalConfigurationRoute
  '/dashboard': typeof PrivateLayoutVerticalDashboardRoute
  '/school': typeof PrivateLayoutVerticalschoolSchoolRoute
  '/school-years': typeof PrivateLayoutVerticalschoolSchoolYearsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_privateLayout': typeof PrivateLayoutRouteWithChildren
  '/init-school': typeof InitSchoolRoute
  '/login': typeof LoginRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/_privateLayout/_cleanLayout': typeof PrivateLayoutCleanLayoutRouteWithChildren
  '/_privateLayout/_vertical': typeof PrivateLayoutVerticalRouteWithChildren
  '/_privateLayout/_cleanLayout/account_list': typeof PrivateLayoutCleanLayoutAccount_listRoute
  '/_privateLayout/_vertical/configuration': typeof PrivateLayoutVerticalConfigurationRoute
  '/_privateLayout/_vertical/dashboard': typeof PrivateLayoutVerticalDashboardRoute
  '/_privateLayout/_vertical/(school)/school': typeof PrivateLayoutVerticalschoolSchoolRoute
  '/_privateLayout/_vertical/(school)/school-years': typeof PrivateLayoutVerticalschoolSchoolYearsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/init-school'
    | '/login'
    | '/not-authorized'
    | '/account_list'
    | '/configuration'
    | '/dashboard'
    | '/school'
    | '/school-years'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/init-school'
    | '/login'
    | '/not-authorized'
    | '/account_list'
    | '/configuration'
    | '/dashboard'
    | '/school'
    | '/school-years'
  id:
    | '__root__'
    | '/'
    | '/_privateLayout'
    | '/init-school'
    | '/login'
    | '/not-authorized'
    | '/_privateLayout/_cleanLayout'
    | '/_privateLayout/_vertical'
    | '/_privateLayout/_cleanLayout/account_list'
    | '/_privateLayout/_vertical/configuration'
    | '/_privateLayout/_vertical/dashboard'
    | '/_privateLayout/_vertical/(school)/school'
    | '/_privateLayout/_vertical/(school)/school-years'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  InitSchoolRoute: typeof InitSchoolRoute
  LoginRoute: typeof LoginRoute
  NotAuthorizedRoute: typeof NotAuthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_privateLayout': {
      id: '/_privateLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/init-school': {
      id: '/init-school'
      path: '/init-school'
      fullPath: '/init-school'
      preLoaderRoute: typeof InitSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-authorized': {
      id: '/not-authorized'
      path: '/not-authorized'
      fullPath: '/not-authorized'
      preLoaderRoute: typeof NotAuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_privateLayout/_cleanLayout': {
      id: '/_privateLayout/_cleanLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutCleanLayoutRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/_vertical': {
      id: '/_privateLayout/_vertical'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutVerticalRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_privateLayout/_cleanLayout/account_list': {
      id: '/_privateLayout/_cleanLayout/account_list'
      path: '/account_list'
      fullPath: '/account_list'
      preLoaderRoute: typeof PrivateLayoutCleanLayoutAccount_listRouteImport
      parentRoute: typeof PrivateLayoutCleanLayoutRoute
    }
    '/_privateLayout/_vertical/configuration': {
      id: '/_privateLayout/_vertical/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof PrivateLayoutVerticalConfigurationRouteImport
      parentRoute: typeof PrivateLayoutVerticalRoute
    }
    '/_privateLayout/_vertical/dashboard': {
      id: '/_privateLayout/_vertical/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateLayoutVerticalDashboardRouteImport
      parentRoute: typeof PrivateLayoutVerticalRoute
    }
    '/_privateLayout/_vertical/(school)/school': {
      id: '/_privateLayout/_vertical/(school)/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof PrivateLayoutVerticalschoolSchoolRouteImport
      parentRoute: typeof PrivateLayoutVerticalRoute
    }
    '/_privateLayout/_vertical/(school)/school-years': {
      id: '/_privateLayout/_vertical/(school)/school-years'
      path: '/school-years'
      fullPath: '/school-years'
      preLoaderRoute: typeof PrivateLayoutVerticalschoolSchoolYearsRouteImport
      parentRoute: typeof PrivateLayoutVerticalRoute
    }
  }
}

interface PrivateLayoutCleanLayoutRouteChildren {
  PrivateLayoutCleanLayoutAccount_listRoute: typeof PrivateLayoutCleanLayoutAccount_listRoute
}

const PrivateLayoutCleanLayoutRouteChildren: PrivateLayoutCleanLayoutRouteChildren =
  {
    PrivateLayoutCleanLayoutAccount_listRoute:
      PrivateLayoutCleanLayoutAccount_listRoute,
  }

const PrivateLayoutCleanLayoutRouteWithChildren =
  PrivateLayoutCleanLayoutRoute._addFileChildren(
    PrivateLayoutCleanLayoutRouteChildren,
  )

interface PrivateLayoutVerticalRouteChildren {
  PrivateLayoutVerticalConfigurationRoute: typeof PrivateLayoutVerticalConfigurationRoute
  PrivateLayoutVerticalDashboardRoute: typeof PrivateLayoutVerticalDashboardRoute
  PrivateLayoutVerticalschoolSchoolRoute: typeof PrivateLayoutVerticalschoolSchoolRoute
  PrivateLayoutVerticalschoolSchoolYearsRoute: typeof PrivateLayoutVerticalschoolSchoolYearsRoute
}

const PrivateLayoutVerticalRouteChildren: PrivateLayoutVerticalRouteChildren = {
  PrivateLayoutVerticalConfigurationRoute:
    PrivateLayoutVerticalConfigurationRoute,
  PrivateLayoutVerticalDashboardRoute: PrivateLayoutVerticalDashboardRoute,
  PrivateLayoutVerticalschoolSchoolRoute:
    PrivateLayoutVerticalschoolSchoolRoute,
  PrivateLayoutVerticalschoolSchoolYearsRoute:
    PrivateLayoutVerticalschoolSchoolYearsRoute,
}

const PrivateLayoutVerticalRouteWithChildren =
  PrivateLayoutVerticalRoute._addFileChildren(
    PrivateLayoutVerticalRouteChildren,
  )

interface PrivateLayoutRouteChildren {
  PrivateLayoutCleanLayoutRoute: typeof PrivateLayoutCleanLayoutRouteWithChildren
  PrivateLayoutVerticalRoute: typeof PrivateLayoutVerticalRouteWithChildren
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateLayoutCleanLayoutRoute: PrivateLayoutCleanLayoutRouteWithChildren,
  PrivateLayoutVerticalRoute: PrivateLayoutVerticalRouteWithChildren,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  InitSchoolRoute: InitSchoolRoute,
  LoginRoute: LoginRoute,
  NotAuthorizedRoute: NotAuthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
